Add support for disabling few website features
jhaals/yopass pull request #1597
Opened 2023-02-15 00:42 UTC by Neverous

This adds build time toggles for disabling:

- Features cards - seems mostly like an ad, not really useful in custom deployments and can be confusing to users (great on the official one though to learn what this project is :+1:)
- "One-click link" - disabling it makes for easier enforcement of using multiple communication channels when sharing secrets

2024-01-08 22:04 UTC, DracoBlue commented
Hey @jhaals!

What do you think about those changes? 

For our deployment we need to be able to disable the "one-click" link - thus this PR would also fix me use case :).

Best regards

2024-05-06 12:30 UTC, donserdal commented
Hey @jhaals! 
Would love to see this in the official release!

2024-10-11 13:44 UTC, jhaals requested changes
Thanks for the PR and sorry for the delay, I have been away on parental leave so these things have been put on hold. I think this make sense, would you or someone else interested in this feature be so kind and change the name of the environment variables to start with YOPASS_ instead of REACT_APP(I should update the other too but that will be breaking).

2024-10-11 13:44 UTC, jhaals commented on website/README.md
> +- `REACT_APP_DISABLE_ONE_CLICK_LINK=1` - Allows disabling "One-click link" support
```suggestion
- `YOPASS_DISABLE_FEATURES_CARDS=1` - Allows disabling Features cards
- `YOPASS_DISABLE_ONE_CLICK_LINK=1` - Allows disabling "One-click link" support
```

2024-10-11 19:59 UTC, Neverous commented
Tried doing that but I think the `REACT_APP_` prefix is the requirement of the framework [used](https://create-react-app.dev/docs/adding-custom-environment-variables/)? Because it doesn't work without it. I'm not that familiar with it to figure out what else needs changing but just renaming the envs I added to `YOPASS_*`  stops them from working :disappointed:

2024-10-12 17:25 UTC, jhaals commented
Thanks 👏

2024-10-12 17:28 UTC, jhaals commented
@Neverous just a small think left to fix.

```
[warn] src/Routing.tsx
[warn] vite.config.ts
[warn] Code style issues found in 2 files. Run Prettier with --write to fix.
```

2025-02-14 09:55 UTC, gefloh commented
@jhaals @Neverous Would also really love to see this feature, please push this forward. Thanks.

2025-02-14 17:40 UTC, Neverous commented
I don't think its waiting for anything from me, its ready to be merged @jhaals ?
But I rebased it just in case :thinking:

2025-03-12 10:15 UTC, merged