Migrate from CRA to Vite
jhaals/yopass pull request #1871
Opened 2023-09-14 07:17 UTC by fritzfr

This PR replaces the recently deprecated Create-React-App (react-scripts) with [Vite](https://vitejs.dev/).
This also allows to upgrade Typescript afterwards (https://github.com/jhaals/yopass/pull/1841).

2023-09-14 10:13 UTC, jhaals requested changes
Very nice to see this change! 👏 

Just some small tweaks required by prettier and then let's ship this!

2023-09-14 10:13 UTC, jhaals commented on website/package.json
> +    "build": "vite",
```suggestion
    "build": "vite build",
```

2023-09-14 11:04 UTC, fritzfelix commented on website/package.json
> +    "build": "vite",
@jhaals Check the updated diff :)

2023-09-14 11:05 UTC, fritzfr commented on website/package.json
> +    "build": "vite",
Check the updated diff 👍

2023-09-17 06:45 UTC, jhaals approved these changes

2023-09-17 06:45 UTC, merged